export const SUGGESTION_REQUEST = 'SUGGESTION_REQUEST';
export const SUGGESTION_FAILURE = 'SUGGESTION_FAILURE';
export const SUGGESTION_SUCCESS = 'SUGGESTION_SUCCESS';
export const SUGGESTION = 'SUGGESTION';
